version: "3.7"
services:
  server:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - default
    ports:
      - "8080:8080"
    command: ["sh", "-c", "/cmd/bin/migrate up && /cmd/bin/api"]

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: posts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgresql: